### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen-GO-Plus#1]
Ikemen GO is compatible with .ogg music files, but isn't compatible with any other audio format -except for .wav that are used for characters sounds-.

There are some golang libraries to decode mp3 files, for example [hajimehoshi's](https://github.com/hajimehoshi/go-mp3) and [faiface's](https://github.com/faiface/beep) ones.

The problem is that Ikemen GO uses an OpenAL implementation to play music and there is no documentation or comments about how it works, making it difficult to implement.

**Comment by K4thos** [comment]
If someone is going to help with sound part of the engine I think it's worth considering recoding sound.go to use github.com/faiface/beep (or maybe github.com/go-audio if it develops further) instead of github.com/jfreymuth/go-vorbis/ogg/vorbis and github.com/timshannon/go-openal/openal packages, considering current implementation is dependent upon OpenAL 1.1 Windows Installer (zip) - without it the engine crashes. Package that works completely independently would make compiling code for different systems easier. Unified functions for volume and looping would be useful for option screen and accurate mugen screenpack implementation. Current sound code also has annoying ducking effect when more than 1 sound play at the same time, not sure if it can be easily fixed with openal package.
This discussion may be worth reading: https://github.com/go-audio/audio/issues/3
Example usage of beep: https://faiface.github.io/post/how-i-built-audio-lib-composite-pattern/
