### ISSUE TITLE
What is the Licence for this Project?

### ISSUE THREAD

**Issue by Pumpkin1988** [K4thos/Ikemen-GO-Plus#15]
I do not see a license listed in the source code. Could you please clarify. Thank you.

**Comment by shinlucho** [comment]
This is a fork of [Suehiro's Ikemen GO](https://osdn.net/users/supersuehiro/pf/ikemen_go/wiki/FrontPage) repository, which also doesn't have any license listed.

I'll try to contact him to see if origin repo uses a BSD license like in his old repo or any other similar license, mostly to avoid problems in the future.

**Comment by Pumpkin1988** [comment]
Thank you. That would be awesome! Please reply with response.

**Comment by Pumpkin1988** [comment]
Any response yet?

**Comment by shinlucho** [comment]
Nope, still no answers. Sent him a message on OSDN and tried to create a pull request, but OSDN has some problems with it, so nothing new for now.

**Comment by Pumpkin1988** [comment]
Thank you for your effort. It was nice of you to try. I may decide to check back at some later date. But, as it stands, it's already been a week and I think it's best for me to not hold onto any hope for a resolution to this.

The message boards in general are basically ambivalent to the issue. They have code, so they don't care to know legally what they can and can not do with it and instead are fine to just assume they have rights with it that they may, or may not, have. We'll likely never know.

I am glad to have spoken with you. You knew where to go to ask and actually tried to get a direct answer. Which is more than I can do. Thank you for your time and best wishes.

**Comment by pumpkin1991** [comment]
Sorry, I lost my original login information.

At any rate, I am wondering if you are any closer to an answer. I was going to try to e-mail him myself, but can not find a way to do it. I have prepared a statement.

"Hello. Thank you for creating the amazing Ikemen Go.

 What is the software license for Ikemen Go? Can you please include the software license in your source code so that it is clear for everyone to read?

I have asked around and no one seems to really know. Some people say it is BSD. Some say it is MIT. Other people simply do not know.

It is important to know what the license to this amazing software is so that we know what we are allowed to do with it. Currently, we are just assuming generic "open source" without anything official as you have not provided a license.

If you intend for others to have liberty to modify and build on this software then you should post a licence that makes that intent clear so that we know that it is legally safe for us to do so.

Thank you for your time and I apologize for using Google Translate as my Japanese is very basic from High School and I don't know how to ask this question on my own."

Here is the Google Translate of this statement for your convenience.

"こんにちは。素晴らしいIkemen Goを作成していただきありがとうございます。

 Ikemen Goのソフトウェアライセンスは何ですか？誰もが読むことができるように、ソースコードにソフトウェアライセンスを含めてください。

私は尋ねたところ、誰も本当に知っているようではない。 BSDだと言う人もいます。 MITだと言う人もいます。他の人は単に知らない。

この驚くべきソフトウェアのライセンスが何であるかを知ることが重要であり、私たちがそのソフトウェアを使って何ができるのかを知ることが重要です。現在、あなたはライセンスを提供していないので、公式のものなしで一般的な "オープンソース"を想定しています。

他の人がこのソフトウェアを改造して構築する自由を得ようとしている場合は、その意図を明確にするライセンスを掲示して、そうすることが法的に安全であることを知る必要があります。

ありがとう、ありがとう、私は日本語が高校から非常に基本的なので私はGoogle翻訳を使用することをお詫びし、私は自分自身でこの質問をする方法を知らない。"

It sounds like from what you said that you know how to contact Suehiro. Can you please ask him for clarification again? Thank you.

**Comment by pumpkin1991** [comment]
Ok, sent a larger e-mail directly to him on OSDN. Dead God I hope Google Translate works.

スエヒロさん、

IkemenとIkemenはどんなライセンスですか？

私はあなたのソフトウェアを楽しむので頼みます。それは驚くべきことです。私はコミュニティがその周りに成長するのを見たいと思います。

しかし、悲しいことに、あなたはライセンスがリストされていません。これは、著作権法の崩壊の奇跡のために問題である。

https://www.gnu.org/licenses/license-list.en.html

「ソースコードにユーザーに4つの本質的な自由を与えるライセンスがない場合、明示的かつ有効にパブリックドメインに置かれていない限り、フリーソフトウェアではありません。

一部の開発者は、ライセンスのないコードはパブリックドメインに自動的に存在すると考えています。それは今日の著作権法では当てはまりません。むしろ、著作権で保護されているすべての作品は、デフォルトで著作権があります。これにはプログラムが含まれます。ユーザーに自由を与えるためのライセンスがなければ、彼らは何も持っていません。一部の国では、ライセンスなしでコードをダウンロードするユーザーは、単にコンパイルまたは実行するだけで著作権を侵害する可能性があります。

プログラムを無料にするためには、著作権者は4つの本質的な自由を明示的にユーザーに与えなければなりません。彼らが行う文書は、フリーソフトウェアライセンスと呼ばれます。これがフリーソフトウェアライセンスの目的です。

一部の国では、著作者がパブリックドメインにコードを入れることができますが、それには明示的な処置が必要です。そうしたい場合は、CC0を使用することをお勧めします。CC0は、他の国でもパブリックドメインとほぼ同等のライセンスを設定して動作します。しかし、ほとんどの場合、自由がコードのすべてのユーザーに届くことを保証するために、コードをコピーレフトする方がよい」

実際、あなたのソフトウェアは本質的に独占的なソフトウェアであり、たまたま私たちが読むことができるソースコードを持っています。しかし、あなたがライセンスを別途記載しない限り、それは "Free / Libre Software"または "Open Source"ではありません。パブリックドメインでもありません。法律は、元の著者が別途免許で別途記載していない限り、元の著者に属する完全な所有権を有するものとします。少なくとも、これが米国著作権法のしくみです。日本での生活や国際的な著作権法との関係については不明です。しかしどちらの方法でも、ライセンスはソフトウェアの目的が合法であることを合法的に示すため、すべてを明確にします。

残りのお客様には、現在、このソフトウェアの修正版（フォーク）、または販売コピーの修正、再配布、頒布の法的権利はありません。

基本的に、私たちが法的に行うことができるのは、それをダウンロードし、それがどのように動作し、それを実行するかということだけです。他に何もない。

人々はそれが「オープンソース」であると想定しており、Ikemen PlusとIkemen Go Plusにそれをフォークしていますが、本当にその権利を行使することができないライセンスをリリースしていないと感じています。とにかく彼らは前提を作り、やっているだけです。

私は、ソフトウェアをGNU GPL、MIT、BSDなどの「オープンソース」のようなものにしようと思っています。私はあなたのソフトウェアを構築し、あなたのソフトウェアをフォークする人々を歓迎すると仮定しています。しかし、あなたがそうしない場合は、事前に知っておいて怒らないようにして、後で皆を訴えることを選ぶことをお勧めします。

ライセンスがなければ、ソフトウェアをそのように使用するつもりがない場合でも、後であなたの訴えを受けるリスクなしに、ソフトウェアで法的にできることはわかりません。

ライセンスを選択してIkemenとIkemen Goの両方のソースコードに置いてみれば、私たち全員がライセンスをはっきりと読んで、あなたが持っているこの素晴らしいソフトウェアを法的にどのように使用することができるかを知ることができます。作成した。

Google翻訳を使用して申し訳ありませんが、高校の日本語は非常に基本的です。また、このことについてお手数をおかけして申し訳ありません。このような驚くべきゲームエンジンを作るためには、時間がかかり、あなたの仕事が必要だったに違いない。彼らはこれまで私が見たこととは違っている。

しかし、これは本当に重要な問題です。私が無限の場面を離れた理由は、無限の免許がどのように独占的であったかが好きではなかったからです。コミュニティ全体が、ユーザーが作成したコミュニティコンテンツでMugenを中心に成長しました。これらの人々とそのコンテンツは、コミュニティライセンスエンジンを実行する必要があります。何年もの間、それは独占的なMugenエンジンとライセンスの後ろに閉じ込められています。

あなたのエンジンを見たとき、それはミュゲンがやることができるすべてのことをすることができました！それはオンラインで遊んでいました！私は何年も夢を見てきたので、私から離れた国に住む父とミュンヘンを演奏できるようになりました。

あなたのソフトウェアは私が望んでいたすべてのものでしたが、ライセンスは明確に述べられていません。だから、私はMugenのコンテンツにコミュニティにやさしいライセンスエンジンを提供することを望んだが、免許は必要ない。

無限のフォークストリームが発生する前に、この問題が解消されることが重要です。ソフトウェアのライセンスを知っている人も誰も知りません。一部のライセンスでは、GNU GPLのような元のプログラムと同じライセンスを使用する派生的な作業が必要となるためです。ライセンスがソースコードに置かれる前にこれらのフォークが起き続けると、どのように強制されますか？

私はちょうどライセンスが選択され、ソースに置かれていることがコミュニティにとって最良だと思う


Dear Suehiro,

What license is Ikemen and Ikemen Go under?

I ask because I enjoy your software. It is amazing and I'd like to see a community grow around it.

However, sadly, you do not have a license listed. This is a problem because of the fallowing quirk in copyright law.

https://www.gnu.org/licenses/license-list.en.html

"If source code does not carry a license to give users the four essential freedoms, then unless it has been explicitly and validly placed in the public domain, it is not free software.

Some developers think that code with no license is automatically in the public domain. That is not true under today's copyright law; rather, all copyrightable works are copyrighted by default. This includes programs. Absent a license to grant users freedom, they don't have any. In some countries, users that download code with no license may infringe copyright merely by compiling it or running it.

In order for a program to be free, its copyright holders must explicitly grant users the four essential freedoms. The document with which they do so is called a free software license. This is what free software licenses are for.

Some countries allow authors to put code in the public domain, but that requires explicit action. If you wish to do that, the method we recommend is to use CC0, which also works in other countries by putting on a license that is more or less equivalent to public domain. However, in most cases it is better to copyleft your code to assure that freedom reaches all users of the code."

So, in effect, your software is essentially proprietary software that just happens to have its source code available for us to read. But, unless you state otherwise with a license, it is not "Free/Libre Software" or "Open Source." It is not even public domain. The law assumes full propitiatory ownership to belong to the original author unless the original author specifically states otherwise with a license. At least, that’s how United States copyright law works. Not sure how that works with you living in Japan and international copyright law. But, either way, a license would make everything clear because it would legally show what your intent is for the software.

The rest of us currently have no legal right to modify, redistribute, distribute modified versions (forking) , or sale copies of this software. 

Essentially, all we can legally do is download it, see how it works, and run it. Nothing else at all.

People are assuming it is "open source" and are forking it into Ikemen Plus and Ikemen Go Plus, but sense you have not released a license they really don't have the legal right to do that. They're just making assumptions and doing it anyway.

I'm assuming that you intend the software to be some sort of "open source" such as GNU GPL, MIT, or BSD. I'm assuming you welcome people building on your software and forking your software. But, in case you don't, it would be nice to know ahead of time so that you don't get angry and choose to sue everyone later.

Without a license, we don't know what we can legally do with the software without risking getting sued by you later if you did not intend for your software to be used that way.

It would be nice if you chose a license and placed it in the source code for both Ikemen and Ikemen Go so that all of us can clearly read the license and know what your intentions are for how we can legally use this amazing software that you have created.

I am sorry to use Google translate, but my Japanese from high school is very basic. Also, I am sorry to bother you about this. It must have taken much time and work from you to make such amazing game engines. They are unlike anything I have ever seen before.

But, this is truly an important issue. The reason I left the Mugen scene was because I did not like how Mugen's license was proprietary. An entire community grew around Mugen with user generated community content. Those people and that content deserve a community licensed engine to run on. For years, it has been trapped behind the proprietary Mugen engine and license.

When I saw your engine, it could do all the things Mugen could do and more! It even had online play! Something I have dreamed of for years so that I could play Mugen with my Dad who lives states away from me.

Your software was everything I was hoping for, but the license is not clearly stated. So, it does everything I hoped it would do in providing a community friendly licensed engine for Mugen content.... but without the license.

It's important that this issue is cleared up before an endless stream of forks happen and no one knows what license the software should be under and it all spirals out of control; as some licenses require derivative works to use the same license as the original program, such as the GNU GPL. How would that be enforced if these forks keep happening before a license is placed in the source code?

I just think it's best for the community that a license be chosen, placed in the source code for everyone to clearly read, and that there is no questions or ambiguity. Everything should be clearly stated.

Thank you again for your time, for your amazing software, and for recognizing the importance of this issue.

**Comment by shinlucho** [comment]
D: damn that was long.

From my part I have no answers yet. I managed to create a pull request with a fix only to call his attention, but no luck.

Let's hope that spamming his OSDN account work someday.

**Comment by shinlucho** [comment]
Bumping this question.

Suehiro updated ikemen go [repository](https://osdn.net/users/supersuehiro/pf/ikemen_go/wiki/FrontPage#h1-License) with a MIT license. :smile: 

We can use the same license specifying it like this [example](https://gist.github.com/tassoevan/8022196). I'm not sure if that's correct or if that isn't necessary and with just a MIT license with suehiro name and year is enough.
