### ISSUE TITLE
How do I Compile?

### ISSUE THREAD

**Issue by pumpkin1991** [K4thos/Ikemen-GO-Plus#18]
How do I compile this from source code on GNU+Linux operating systems?

I am using a .deb based os. I tried opening Terminal and simple running the four files build.bat build.sh get.sh run.sh

I have no idea what order to run these under or if I need to install a "Go Environment" first or what.

Make programs I've compiled before have me reach out and get dependencies either through synaptic package manager or through a long sudo apt-get install so on and so forth. Or, sudo apt-get build-dep program name.

But, I see nothing here as a read me for dependencies or compiling instructions.

Can somebody help please. Thank you.

**Comment by shinlucho** [comment]
With a debian based system, it can be compiled the following way:

1. Install golang:
`sudo apt install golang-go`

2. Install git:
`sudo apt install git`

3. Install [GLFW](https://github.com/go-gl/glfw) dependencies:
`sudo apt install libgl1-mesa-dev xorg-dev`

4. Install OpenAL dependencies:
`sudo apt install libopenal1 libopenal-dev`

5. Download Ikemen GO Plus repository:
`git clone https://github.com/K4thos/Ikemen-GO-Plus.git`

6. Move to downloaded folder:
`cd Ikemen-GO-Plus`
 
7. There are [some problems with linux](https://github.com/K4thos/Ikemen-GO-Plus/issues/17) on main branch, so there is another temporary branch for linux:
`git checkout linux origin-linux`

8. Download that other branch:
`git pull`

9. Execute get.sh to download Ikemen dependencies (it takes a while):
`./get.sh`

10. FINALLY compile:
`./build.sh`

11. And now, Ikemen can be opened double clicking Ikemen-GO-Plus, or with the terminal:
`./Ikemen_GO`

This would be enough for now, later we gonna document the project because there is nothing atm. If you have some error, just let us know.

Enjoy c:

**Comment by danzpaim** [comment]
> Hi, i get this: error:" pathspec 'linux' did not match any file(s) known to git
> error: pathspec 'origin-linux' did not match any file(s) known to git"
> when i enter "git checkout linux origin-linux" in terminal.

I have this problem too!
